image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      export PATH=$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools:$PATH
      mkdir -p /home/gitpod/.android
      touch /home/gitpod/.android/repositories.cfg
    init: |
      npm install